### ISSUE TITLE
[EPIC] Tasks to move sqlparser-rs to apache organization

### ISSUE THREAD

**Issue by alamb** [apache/datafusion-sqlparser-rs#1436]
This ticket tracks the work required to move sqlparser-rs to Apache DataFusion governance. See https://github.com/sqlparser-rs/sqlparser-rs/issues/1294 for backstory and discussion

- [x] Add Apache license headers to all files in repo: https://github.com/sqlparser-rs/sqlparser-rs/pull/1437
- [x] COmplete IP clearance process: https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/datafusion-sqlparser.xml
- [x] Migrate repository to `apache` organization: https://issues.apache.org/jira/browse/INFRA-26136
- [x] https://github.com/apache/datafusion-sqlparser-rs/issues/1423
- [ ] Update readme
- [ ] Update authors, homepage, etc in [Cargo.toml](https://github.com/sqlparser-rs/sqlparser-rs/blob/b9f67847146658aa7a01e39f69ce87d3852e2589/Cargo.toml#L19)
- [ ] Update release process + documentation
- [ ] Update [security reporting information](https://github.com/sqlparser-rs/sqlparser-rs/blob/9648a5271505fdf0a2354aa0871fab43c5722d2f/SECURITY.md#L24)
- [ ] Add RAT / license check to the CI
- [ ] Write a blog post about the donation / migration
- [ ] update the crates.io ownership information
- [ ] Get sqlparser maintainers (@iffyio , @lovasoa and @jmhain ) commit rights

**Comment by alamb** [comment]
Now that we have completed the acceptance process to DataFusion https://github.com/apache/datafusion-sqlparser-rs/issues/1294 (thank you @andygrove ) my plan is:
1. Make one final non apache release - https://github.com/apache/datafusion-sqlparser-rs/issues/1423
2. Then update the various readmes, processes, etc
3. Expect that version 53.0.0 will be the first under the DataFusion governance process

**Comment by alamb** [comment]
This is completed now so closing the ticket
