### ISSUE TITLE
Support all ANSII data types

### ISSUE THREAD

**Issue by AugustoFKL** [apache/datafusion-sqlparser-rs#661]
Support all ANSII data types: https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#_6_1_data_type

- [ ] Predefined type
  - [ ] Character string type
    - [X] `CHARACTER` (complete since [#663](https://github.com/sqlparser-rs/sqlparser-rs/pull/663))
    - [X] `CHAR` (complete since [#663](https://github.com/sqlparser-rs/sqlparser-rs/pull/663))
    - [X] `CHARACTER VARYING` (complete since [#663](https://github.com/sqlparser-rs/sqlparser-rs/pull/663))
    - [X] `CHAR VARYING` (complete since [#663](https://github.com/sqlparser-rs/sqlparser-rs/pull/663))
    - [X] `VARCHAR ` (complete since [#663](https://github.com/sqlparser-rs/sqlparser-rs/pull/663))
    - [ ] `CHARACTER LARGE OBJECT`
    - [ ] `CHAR LARGE OBJECT`
    - [ ] `CLOB`
  - [ ] National character string type
    - [ ] `NATIONAL CHARACTER`
    - [ ] `NATIONAL CHAR`
    - [ ] `NCHAR`
    - [ ] `NATIONAL CHARACTER VARYING`
    - [ ] `NATIONAL CHAR VARYING`
    - [ ] `NCHAR VARYING`
    - [ ] `NATIONAL CHARACTER LARGE OBJECT`
    - [ ] `NCHAR LARGE OBJECT`
    - [ ] `NCLOB`
  - [ ] Binary string type
    - [ ] `BINARY`
    - [ ] `BINARY VARYING`
    - [ ] `VARBINARY`
    - [ ] `BINARY LARGE OBJECT`
    - [ ] `BLOB `
  - [ ] Exact numeric type
    - [ ] `NUMERIC`
    - [ ] `DECIMAL`
    - [ ] `DEC`
    - [ ] `SMALLINT`
    - [ ] `INTEGER`
    - [ ] `INT`
    - [ ] `BIGINT`
  - [ ] Approximate numeric type
    - [ ] `FLOAT` 
    - [ ] `REAL`
    - [ ] `DOUBLE PRECISION`
  - [ ] Decimal floating-point type
    - [ ] `DECFLOAT`
  - [ ] Boolean type
    - [ ] `BOOLEAN`
  - [ ] Datetime type
    - [ ] `DATE`
    - [ ] `TIME`
    - [ ] `TIMESTAMP`
  - [ ] Interval type
    - [ ] `INTERVAL`
- [ ] Row type (depends on `Predefined type`)
- [ ] Path resolved user-defined type
- [ ] Reference type (depends on `Path resolved user-defined type`)
- [ ] Collection types (depends on `Predefined type`)
  - [ ] Array
  - [ ] Multiset
